<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css">
	</head>
	<body>
        <h3>Registration Confirmation</h3>
        <p>Click on the below link to confirm your registration.</p>
        <a href="<?php echo $link; ?>">Complete Registration</a>
    </body>
</html>